### PR TITLE
Update dependency

### PR DESCRIPTION
**Pull request by nodece**

### CODE REVIEW

**Comment by hsluoyz** [comment]
lgtm

**Comment by nodece** [comment]
@hsluoyz Could you call the `npm run deploy` to release new version?

**Comment by hsluoyz** [comment]
@nodece . I can do this this time.

But can we automate it with Travis CI? So I will be freed from this work in future?

**Comment by nodece** [comment]
@hsluoyz Sounds good. I want to use GitHub Action. What do you think?

**Comment by hsluoyz** [comment]
Sure. You can try it. I also want to learn GitHub Actions.

**Pull request merged**
