### PR TITLE
fix: resolve unexpected parse

### PR DESCRIPTION
**Pull request by Zxilly**
Fix: https://github.com/casbin/casbin-editor/issues/45
Fix: https://github.com/php-casbin/php-casbin/issues/90

@techoner @nodece @hsluoyz plz review

Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@stonecool plz review

**Comment by stonecool** [comment]
@hsluoyz I Confirmed, the bug is fixed. Thanks for you guys job.

**Review by techoner — APPROVED** [review]

**Comment by Zxilly** [comment]
@hsluoyz plz merge this

**Pull request merged**
