### PR TITLE
feat: add support for share content

### PR DESCRIPTION
**Pull request by Zxilly**
resolve: #44 

@hsluoyz @nodece plz review

Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Zxilly I want to see the preview for this PR, so maybe this issue needs to be fixed first: https://github.com/casbin/casbin-editor/issues/53

**Comment by hsluoyz** [comment]
@ErikQQY netlify failed, plz fix:

image

**Comment by Zxilly** [comment]
@hsluoyz I didn't rebase the code and cause this bug.

**Comment by hsluoyz** [comment]
@Zxilly it works great now!

Can you add a "click to copy shared URL" functionality?

image

**Comment by Zxilly** [comment]
@hsluoyz Working on this

**Comment by Zxilly** [comment]
@hsluoyz have added

**Comment by nodece** [comment]
@Zxilly This feature doesn't work, casbin-editor can load data from dpaste, but this data cannot load to editor, please fix this feature.

**Comment by Zxilly** [comment]
@nodece I believe it works fine. Maybe you should open the url in a new tab. Open the same url with different hash in the same tab won't take a refresh.
And an implicitly copy action may override the data in the visitor's clipboard. A confirm is necessary.

**Comment by hsluoyz** [comment]
To avoid messing up history, I removed all following commits from git:

image

**Pull request merged**
